[package]
name = "stripe-faker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.18"
async-stripe = { version = "0.14", features = ["runtime-tokio-hyper"] }
fake = "2.5"
rand = "0.8"
tokio = { version = "1.21.2", features = ["full"] }
